### ISSUE TITLE
Game won't load: missing Asset "loading.png"

### ISSUE THREAD

**Issue by jwoehr** [CtrlShiftSammy/Quantum-Chess#1]
```
$ python main.py 
pygame 2.1.0 (SDL 2.0.16, Python 3.8.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 148, in <module>
    loading = pygame.transform.scale(pygame.image.load(os.path.join('Assets', 'loading.png')), (600, 125))
FileNotFoundError: No file 'Assets/loading.png' found in working directory '/Users/jwoehr/work/Qiskit/FallHackathon2021/Quantum-Chess'.
$ ls Assets/
background.jpg	bqb.png    dbbn2.png  dbqp1.png  dbrp2.png  dwqn1.png  dwrn2.png       lbnp2.png  lbrb1.png  lwbp2.png	lwqr1.png   wb.png   wqn.png
bb.png		bqn.png    dbbp1.png  dbqp2.png  dwbn1.png  dwqn2.png  dwrp1.png       lbqb1.png  lbrb2.png  lwnp1.png	lwqr2.png   wbn.png  wqp.png
bbn.png		bqp.png    dbbp2.png  dbqr1.png  dwbn2.png  dwqp1.png  dwrp2.png       lbqb2.png  lbrn1.png  lwnp2.png	lwrb1.png   wbp.png  wqr.png
bbp.png		bqr.png    dbnp1.png  dbqr2.png  dwbp1.png  dwqp2.png  greyreplay.png  lbqn1.png  lbrn2.png  lwqb1.png	lwrb2.png   wk.png   wr.png
bk.png		br.png	   dbnp2.png  dbrb1.png  dwbp2.png  dwqr1.png  lbbn1.png       lbqn2.png  lbrp1.png  lwqb2.png	lwrn1.png   wn.png   wrb.png
bn.png		brb.png    dbqb1.png  dbrb2.png  dwnp1.png  dwqr2.png  lbbn2.png       lbqp1.png  lbrp2.png  lwqn1.png	lwrn2.png   wnp.png  wrk.png
bnp.png		brn.png    dbqb2.png  dbrn1.png  dwnp2.png  dwrb1.png  lbbp1.png       lbqp2.png  lwbn1.png  lwqn2.png	lwrp1.png   wp.png   wrn.png
bp.png		brp.png    dbqn1.png  dbrn2.png  dwqb1.png  dwrb2.png  lbbp2.png       lbqr1.png  lwbn2.png  lwqp1.png	lwrp2.png   wq.png   wrp.png
bq.png		dbbn1.png  dbqn2.png  dbrp1.png  dwqb2.png  dwrn1.png  lbnp1.png       lbqr2.png  lwbp1.png  lwqp2.png	replay.png  wqb.png

**Comment by jwoehr** [comment]
Created a phony `loading.png` but now it crashes like this:
```
$ python main.py 
pygame 2.1.0 (SDL 2.0.16, Python 3.8.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 149, in <module>
    white_wins = pygame.transform.scale(pygame.image.load(os.path.join('Assets', 'whitewins.png')), (500, 100))
FileNotFoundError: No file 'Assets/whitewins.png' found in working directory '/Users/jwoehr/work/Qiskit/FallHackathon2021/Quantum-Chess'.
```

**Comment by Kaustav-B** [comment]
Looks like a few assets were missing, I have added them.

**Comment by CtrlShiftSammy** [comment]
Looks like a few assets were missing, I have added them.

**Comment by jwoehr** [comment]
Works for me, thanks, @CtrlShiftSammy
